## Revision #1 ETL

In [18]:
import pandas as pd
pd.set_option('display.float_format', lambda x: '%.0f' % x)  # evitando notacion científica
aguas = pd.read_parquet('DATA/aguas_publish.pq')
aguas = aguas[aguas.columns[3:]]   # elimina datos irrelevantes para este análisis
aguas.describe(percentiles=[.5,.75,.9,.99,.999]).round(0)   # la cola entre el percentil 99 y el máximo ya es fuerte

,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,...,UTM Norte Captación (m),UTM Este Captación (m),UTM Norte Restitución (m),UTM Este Restitución (m),Distancia,Desnivel (m),N° CBR,Año,¿Posee más de un punto de captación?,CaudalPromedio
count,119843,119559,119525,119910,120671,120664,120604,120558,120545,120396,...,123805,123805,123805,123805,123805,123805,123805,123805,0,123805
mean,520,464,458,510,641,721,696,655,621,627,...,15810712,1645104,2219315,241885,202,15,84,1056,nan,0
std,31106,30881,30970,31154,31304,32641,31466,31280,31153,31211,...,248686547,28961386,95838246,11346283,1175,367,1987,1002,nan,1
min,0,0,0,0,0,0,0,-577,-577,0,...,0,0,0,0,0,0,0,0,nan,0
50%,2,2,2,2,2,2,2,2,2,2,...,5713580,313212,0,0,0,0,3,1989,nan,0
75%,15,15,15,15,17,17,17,17,17,17,...,6190570,673093,0,0,0,0,75,2010,nan,0
90%,75,70,70,78,89,95,95,93,90,90,...,6419315,724096,0,0,0,0,240,2014,nan,0
99%,3500,2973,2650,3200,5370,6271,6100,5500,5000,5000,...,7838882,760024,5996975,737336,5050,295,622,2018,nan,0
99.9%,68124,55849,50000,60182,90821,100000,100000,95057,90000,87379,...,5603170000,692458108,6458910,761010,14126,892,1287,2019,nan,0
max,7904490,7904490,7904490,7904490,7904490,7904490,7904490,7904490,7904490,7904490,...,6689978000,763216000,5621250000,753050000,99999,99999,632002,2019,nan,208

Siguen apareciendo caudales desproporcionadamente altos (8 MM??). Revisemos.

In [19]:
mayores = aguas.sort_values('Enero', ascending=False).head(10)
mayores['Enero']

3975     7904490
114632   6341958
40107    1158500
9726     1090000
77380    1035000
5102     1035000
116369    850000
116794    848400
5101      677000
77379     677000
Name: Enero, dtype: float64

In [20]:
aguas.loc[3975]   # la ficha completa del caso en cuestión

Región                                                                                                Maule
Provincia                                                                                           Linares
Comuna                                                                                              Linares
Nombre Solicitante                                                                             COPIHUE SPA.
Unidad de Resolución/ Oficio/ C.B.R.                                                     1° J. de L. Curico
Fecha de Resolución/ Envío al Juez/ Inscripción C.B.R.                                  2018-04-11 00:00:00
N° Resolución/ Oficio/ Fojas | N° CBR                                                           C-1651-2017
Fecha Toma Razón                                                                                       None
Artículo Transitorio                                                                                   None
Tipo Derecho                                                                                     Consuntivo
Naturaleza del Agua                                                                 Superficial y Corriente
Clasificación Fuente                                                                             Rio/Estero
Uso del Agua                                                                                           None
Cuenca                                                                                            Rio Rapel
SubCuenca                                                   Rio Cachapoal Alto (Hasta bajo junta Rio Claro)
SubSubCuenca                                              Rio Cortaderal en desembocadura Laguna Pejerreyes
Fuente                                                                                           Rio Blanco
Enero                                                                                               7904490
Febrero                                                                                             7904490
Marzo                                                                                               7904490
Abril                                                                                               7904490
Mayo                                                                                                7904490
Junio                                                                                               7904490
Julio                                                                                               7904490
Agosto                                                                                              7904490
Septiembre                                                                                          7904490
Octubre                                                                                             7904490
Noviembre                                                                                           7904490
Diciembre                                                                                           7904490
Ejercicio del Derecho                                                                 Permanente y Continuo
                                                                                ...
Unidad de Caudal                                                                                       Lt/s
¿Caudal Promedio Anual?                                                                                  SI
Caudal Ecológico (l/s)                                                                                 None
¿Caudal Ecológico Promedio?                                                                            None
Acciones en el Cauce                                                                                      0
Acciones en la Fuente                                                                                     0
UTM Norte Captación (m)                                                                             5982500
UTM Este Captación (m)                                                                               259250
Huso                                                                                                     19
Datum                                                                                                  1984
Latitud Captación                                                                                      None
Longitud Captación                                                                                     None
Datum.1                                                                                                None
UTM Norte Restitución (m)                                                                                 0
UTM Este Restitución (m)                                                                                  0
Latitud Restitución                                                                                    None
Longitud Restitución                                                                                   None
Referencia a puntos conocidos de captación                                                             None
Referencia a puntos conocidos de restitución                                                           None
Distancia                                                                                                 0
Unidad Distancia                                                                                       None
Desnivel (m)                                                                                              0
C.B.R.                                                                                        C.B.R. Parral
Fojas                                                                                                    52
N° CBR                                                                                                   37
Año                                                                                                    2016
Código Expediente Antiguo                                                                           (0-0-0)
¿Posee más de un punto de captación?                                                                    NaN
N° Certificado/ Año                                                                               5441/2018
CaudalPromedio                                                                                            8
Name: 3975, Length: 61, dtype: object